import SwiftUI

struct DisclaimerAcceptanceView: View {
    @Environment(NewBackendAuthService.self) private var auth
    let onAccepted: () -> Void

    @State private var isAccepted: Bool = false
    @State private var isSubmitting: Bool = false
    @State private var errorMessage: String?

    private let repository: any DisclaimerRepositoryProtocol = SupabaseDisclaimerRepository(currentVersion: DisclaimerInfo.version)

    var body: some View {
        NavigationStack {
            ZStack {
                VineyardTheme.appBackground.ignoresSafeArea()
                VStack(spacing: 0) {
                    ScrollView {
                        VStack(alignment: .leading, spacing: 16) {
                            header

                            VineyardCard {
                                Text(DisclaimerInfo.bodyText)
                                    .font(.callout)
                                    .foregroundStyle(.primary)
                                    .fixedSize(horizontal: false, vertical: true)
                            }

                            Toggle(isOn: $isAccepted) {
                                Text("I understand and accept")
                                    .font(.headline)
                            }
                            .tint(VineyardTheme.leafGreen)
                            .padding(16)
                            .background(VineyardTheme.cardBackground, in: .rect(cornerRadius: 14))
                            .overlay(
                                RoundedRectangle(cornerRadius: 14)
                                    .stroke(VineyardTheme.cardBorder, lineWidth: 0.5)
                            )

                            if let errorMessage {
                                Label(errorMessage, systemImage: "exclamationmark.triangle.fill")
                                    .font(.footnote)
                                    .foregroundStyle(VineyardTheme.destructive)
                                    .padding(.horizontal, 4)
                            }
                        }
                        .padding(.horizontal, 16)
                        .padding(.vertical, 16)
                    }

                    VStack(spacing: 8) {
                        Button {
                            Task { await accept() }
                        } label: {
                            HStack {
                                if isSubmitting { ProgressView().tint(.white) }
                                Text(isSubmitting ? "Saving…" : "Continue")
                            }
                        }
                        .buttonStyle(.vineyardPrimary)
                        .disabled(!isAccepted || isSubmitting)
                        .opacity((!isAccepted || isSubmitting) ? 0.6 : 1)

                        Text("Disclaimer version \(DisclaimerInfo.version)")
                            .font(.caption2)
                            .foregroundStyle(.secondary)
                    }
                    .padding(.horizontal, 16)
                    .padding(.bottom, 16)
                }
            }
            .navigationTitle("Disclaimer")
            .navigationBarTitleDisplayMode(.inline)
        }
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(spacing: 10) {
                Image(systemName: "exclamationmark.shield.fill")
                    .font(.title2)
                    .foregroundStyle(.orange)
                Text(DisclaimerInfo.title)
                    .font(.title3.weight(.bold))
            }
            Text("Please read carefully before using VineTrack.")
                .font(.subheadline)
                .foregroundStyle(.secondary)
        }
    }

    private func accept() async {
        errorMessage = nil
        isSubmitting = true
        defer { isSubmitting = false }
        do {
            try await repository.acceptCurrentDisclaimer(
                version: DisclaimerInfo.version,
                displayName: auth.userName,
                email: auth.userEmail
            )
            onAccepted()
        } catch {
            errorMessage = error.localizedDescription
        }
    }
}

enum DisclaimerInfo {
    static let version: String = "1.0"
    static let title: String = "Important Vineyard Management Disclaimer"

    static let bodyText: String = """
VineTrack is designed to help record vineyard activities, observations, spray records, trips, calculations, and operational notes.

All records, calculations, recommendations, alerts, and reports generated by VineTrack are provided as practical tools only. They may contain errors, omissions, outdated information, or assumptions based on the data entered by the user.

You remain responsible for all vineyard management decisions, including chemical use, spray timing, withholding periods, worker safety, environmental compliance, irrigation decisions, disease management, and regulatory record keeping.

Before applying any agricultural chemical or treatment, always read and follow the current product label, permit conditions, safety data sheet, local regulations, and any relevant advice from a qualified agronomist or professional adviser.

Weather, disease, irrigation, yield, growth-stage, and spray calculations are estimates only and should not be relied on as the sole basis for operational, financial, safety, or compliance decisions.

VineTrack does not replace professional advice, product labels, legal requirements, or your own vineyard judgement.

By continuing, you acknowledge that you are responsible for checking all information and using VineTrack appropriately for your vineyard, region, and regulatory requirements.
"""
}
