import Foundation

/// Saved breakdown of a single trip's estimated cost across a (paddock, variety)
/// slice. Generated by `TripCostAllocationCalculator` from a `TripCostService.Result`
/// and persisted to `trip_cost_allocations`.
///
/// Financial data — access is gated to owners/managers in UI, sync, and at the
/// Supabase row level (see `sql/059_trip_cost_allocations.sql`).
nonisolated enum TripCostAllocationBasis: String, CaseIterable, Codable, Sendable {
    case area
    case varietyPercentage = "variety_percentage"
    case rowCoverage = "row_coverage"
    case manual

    var displayName: String {
        switch self {
        case .area: return "Area"
        case .varietyPercentage: return "Variety %"
        case .rowCoverage: return "Row coverage"
        case .manual: return "Manual"
        }
    }
}

nonisolated enum TripCostAllocationStatus: String, CaseIterable, Codable, Sendable {
    case complete
    case partial
    case unavailable
}

nonisolated struct TripCostAllocation: Codable, Identifiable, Sendable, Hashable {
    let id: UUID
    var vineyardId: UUID
    var tripId: UUID
    var seasonYear: Int
    var tripFunction: String?

    var paddockId: UUID?
    var paddockName: String?

    var variety: String?
    var varietyId: UUID?
    /// Variety share of this paddock, 0...1.
    var varietyPercentage: Double?
    /// Hectares attributed to this slice (paddockAreaHa * varietyShare).
    var allocationAreaHa: Double?

    var labourCost: Double?
    var fuelCost: Double?
    var chemicalCost: Double?
    var inputCost: Double?
    var totalCost: Double?

    var costPerHa: Double?
    var yieldTonnes: Double?
    var costPerTonne: Double?

    var allocationBasis: TripCostAllocationBasis
    var costingStatus: TripCostAllocationStatus?
    var warnings: [String]
    var calculatedAt: Date
    var sourceTripUpdatedAt: Date?

    init(
        id: UUID = UUID(),
        vineyardId: UUID,
        tripId: UUID,
        seasonYear: Int,
        tripFunction: String? = nil,
        paddockId: UUID? = nil,
        paddockName: String? = nil,
        variety: String? = nil,
        varietyId: UUID? = nil,
        varietyPercentage: Double? = nil,
        allocationAreaHa: Double? = nil,
        labourCost: Double? = nil,
        fuelCost: Double? = nil,
        chemicalCost: Double? = nil,
        inputCost: Double? = nil,
        totalCost: Double? = nil,
        costPerHa: Double? = nil,
        yieldTonnes: Double? = nil,
        costPerTonne: Double? = nil,
        allocationBasis: TripCostAllocationBasis = .area,
        costingStatus: TripCostAllocationStatus? = nil,
        warnings: [String] = [],
        calculatedAt: Date = Date(),
        sourceTripUpdatedAt: Date? = nil
    ) {
        self.id = id
        self.vineyardId = vineyardId
        self.tripId = tripId
        self.seasonYear = seasonYear
        self.tripFunction = tripFunction
        self.paddockId = paddockId
        self.paddockName = paddockName
        self.variety = variety
        self.varietyId = varietyId
        self.varietyPercentage = varietyPercentage
        self.allocationAreaHa = allocationAreaHa
        self.labourCost = labourCost
        self.fuelCost = fuelCost
        self.chemicalCost = chemicalCost
        self.inputCost = inputCost
        self.totalCost = totalCost
        self.costPerHa = costPerHa
        self.yieldTonnes = yieldTonnes
        self.costPerTonne = costPerTonne
        self.allocationBasis = allocationBasis
        self.costingStatus = costingStatus
        self.warnings = warnings
        self.calculatedAt = calculatedAt
        self.sourceTripUpdatedAt = sourceTripUpdatedAt
    }

    nonisolated enum CodingKeys: String, CodingKey {
        case id, vineyardId, tripId, seasonYear, tripFunction
        case paddockId, paddockName
        case variety, varietyId, varietyPercentage, allocationAreaHa
        case labourCost, fuelCost, chemicalCost, inputCost, totalCost
        case costPerHa, yieldTonnes, costPerTonne
        case allocationBasis, costingStatus, warnings, calculatedAt, sourceTripUpdatedAt
    }

    nonisolated init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(UUID.self, forKey: .id)
        vineyardId = try c.decode(UUID.self, forKey: .vineyardId)
        tripId = try c.decode(UUID.self, forKey: .tripId)
        seasonYear = try c.decodeIfPresent(Int.self, forKey: .seasonYear) ?? 0
        tripFunction = try c.decodeIfPresent(String.self, forKey: .tripFunction)
        paddockId = try c.decodeIfPresent(UUID.self, forKey: .paddockId)
        paddockName = try c.decodeIfPresent(String.self, forKey: .paddockName)
        variety = try c.decodeIfPresent(String.self, forKey: .variety)
        varietyId = try c.decodeIfPresent(UUID.self, forKey: .varietyId)
        varietyPercentage = try c.decodeIfPresent(Double.self, forKey: .varietyPercentage)
        allocationAreaHa = try c.decodeIfPresent(Double.self, forKey: .allocationAreaHa)
        labourCost = try c.decodeIfPresent(Double.self, forKey: .labourCost)
        fuelCost = try c.decodeIfPresent(Double.self, forKey: .fuelCost)
        chemicalCost = try c.decodeIfPresent(Double.self, forKey: .chemicalCost)
        inputCost = try c.decodeIfPresent(Double.self, forKey: .inputCost)
        totalCost = try c.decodeIfPresent(Double.self, forKey: .totalCost)
        costPerHa = try c.decodeIfPresent(Double.self, forKey: .costPerHa)
        yieldTonnes = try c.decodeIfPresent(Double.self, forKey: .yieldTonnes)
        costPerTonne = try c.decodeIfPresent(Double.self, forKey: .costPerTonne)
        allocationBasis = (try? c.decodeIfPresent(TripCostAllocationBasis.self, forKey: .allocationBasis)) ?? .area
        costingStatus = try c.decodeIfPresent(TripCostAllocationStatus.self, forKey: .costingStatus)
        warnings = try c.decodeIfPresent([String].self, forKey: .warnings) ?? []
        calculatedAt = try c.decodeIfPresent(Date.self, forKey: .calculatedAt) ?? Date()
        sourceTripUpdatedAt = try c.decodeIfPresent(Date.self, forKey: .sourceTripUpdatedAt)
    }
}
